- public/lib/downloadHttpConcurrent.js
- public/lib/downloadHttpConcurrentProgress.js
- public/lib/downloadProbeTest.js
- public/lib/latencyHttpTest.js
- public/lib/latencyWebSocketTest.js
- public/lib/uploadHttpConcurrent.js
- public/lib/xmlhttprequest.js
Why: JSHint is throwing validation errors on files under lib
How: Fix JSHint errors
> Fix jshint errors

- public/speed-testJS.js
Perform only 10 runs for latency and report the minimum value
> Report minimum value for latency and only perform 10 runs

- Gruntfile.js
Why: need to include controllers folder in grunt package command
How: update grunt to include folder
Test: run grunt package and verify controllers folder is a subfolder of dist folder.
> Update Grunt to package controller folder

- package.json
Why: Change package name and add correct values
How: Update package.json
Test: Verify values are in package.json
> Update name author and license in package.json

- package.json
- public/lib/uploadHttpConcurrentProgress.js
- public/lib/xmlhttprequest.js
Why: code cleanup to remove hardcoded value
How: move value to variable
Test: run upload test to verify functionality
> Move hardcoded value to variable

- package.json
Removing grunt from package.json
> Remove grunt

- package.json
- public/examples/upload/uploadApp.js
- public/lib/downloadProbeTest.js
- public/lib/uploadHttpConcurrentProgress.js
- public/lib/uploadProbeTest.js
- public/speed-testJS.js
Why: Upload testing needs to be updated for reporting low bandwidth clients and bug fix for upload probing
How: Update upload probing and check in uploads test suite to for requests which an onload event occurs but no progress events were recorded.
Test: run upload testing under low bandwidth conditions
> Update uploads workflow

- package.json
- public/lib/webSocket.js
Fix Jshint errors and spacing in the websocket file
> Fix Jshint errors and spacing

- package.json
- public/examples/latency/latencyApp.js
- public/examples/upload/uploadApp.js
- public/lib/latencyBasedRouting.js
- public/speed-testJS.js
Set timeout value for a database call. As the test it getting struck when we don't get response back from the server.
> Set timeout for making call to database

- package.json
- public/examples/download/downloadApp.js
- public/examples/upload/uploadApp.js
- public/lib/calculateStats.js
- public/speed-testJS.js
Update calculator end point to have the url configurable
> Update calculator end point to have the url configurable

- package.json
- public/lib/uploadProbeTest.js
Update the payload function for upload probe
> Update payload function

- package.json
- public/lib/xmlhttprequest.js
Need to have different ProgressInterval for uploads
> Add progressInterval for uplaods

- public/speed-testJS.js
Why: main speedtest page not running correctly
How: update test workflow correctly
Test: run locally and verify entire test runs
> Fix main speedtest page

- controllers/TestPlanController.js
- controllers/UploadController.js
- index.js
- package.json
- public/examples/upload/index.html
- public/examples/upload/uploadApp.js
- public/lib/uploadHttpConcurrentProgress.js
- public/lib/uploadHttpMicrosoft.js
- public/lib/xmlhttprequest.js
- public/speed-testJS.js
Why: Increase accuracy for uploads
How: update workflow to shorten test time and accuracy
Test: run locally or deploy to stage and test with
> Faster uploads

- package.json
- public/examples/upload/uploadApp.js
- public/index.html
- public/lib/uploadHttpConcurrentProgress.js
- public/speed-testJS.js
Why: Fix jshint issues in the uploads
How: Fix the issues and remove unused callbacks
> Jshnit fixes and removing unused callbacks

- README.md
Headers weren't properly formatted.
> Fixed formatting errors

- package.json
- public/lib/downloadHttpConcurrentProgress.js
- public/lib/uploadHttpConcurrentProgress.js
- public/lib/uploadHttpMicrosoft.js
Need to clear interval the when the abortAll the requests.
Defect ID: DE178488
> update abortAll to clear the monitor

- package.json
- public/lib/statisticalCalculator.js
> Fix jshint issues

- package.json
- public/examples/upload/uploadApp.js
- public/lib/uploadHttpConcurrentProgress.js
- public/lib/xmlhttprequest.js
- public/speed-testJS.js
Update uploads test for inconsistent results at lower bandwidths.
> Refactor uploads test

- package.json
- Updated License to match SPDX format
- Added repository
> Fix for warnings during npm install

- package.json
- public/lib/xmlhttprequest.js
NOTE: Changing because it doesn't work with IE browser
> Changing the timeout to be after opening the connection
